alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'
alias .......='cd ../../../../../..'
alias cd.='cd ..'
alias cd..='cd ..'
alias ls='exa'
alias cdiff='colordiff'
alias ra='joshuto'
# alias nvimn='nvim -u NONE -N'
# alias vimn='vim -u NONE -N'
alias l='exa -al'
alias sudo='sudo -E'
alias s='neofetch'
alias t='tmux'
alias pip='pip3'
alias lg="lazygit"
alias cl='clear'
alias ipy="ipython"
alias u="brew update && brew upgrade && brew upgrade --cask"

