PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
PATH="/usr/local/opt/findutils/libexec/gnubin:$PATH"
PATH="/usr/local/opt/gnu-which/libexec/gnubin:$PATH"
PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
PATH="/usr/local/opt/gnu-tar/libexec/gnubin:$PATH"
PATH="/usr/local/opt/grep/libexec/gnubin:$PATH"
PATH="/usr/local/opt/curl/bin:$PATH"
# terminfo
PATH="/usr/local/opt/ncurses/bin:$PATH"
PATH="/usr/local/opt/llvm/bin:$PATH"
PATH="/usr/local/opt/inetutils/libexec/gnubin:$PATH"
# PATH="/usr/local/opt/node@14/bin:$PATH"
