# export SHELL='/usr/local/bin/zsh'
export VISUAL='nvim'
export HOMEBREW_NO_AUTO_UPDATE=1
export GPG_TTY=$(tty)
export XDG_CONFIG_HOME="$HOME/.config"
# homebrew bottle orgin
export HOMEBREW_BREW_GIT_REMOTE="https://mirrors.ustc.edu.cn/brew.git"
export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.ustc.edu.cn/homebrew-bottles"
export HOMEBREW_API_DOMAIN="https://mirrors.ustc.edu.cn/homebrew-bottles/api"
export DBUS_SESSION_BUS_ADDRESS="unix:path=$DBUS_LAUNCHD_SESSION_BUS_SOCKET"

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

alias asciicast2gif='docker run --rm -v $PWD:/data asciinema/asciicast2gif'
source ~/.config/zsh/path.zsh
source ~/.config/zsh/java.zsh
source ~/.config/zsh/go.zsh
source ~/.config/zsh/zim.zsh
source ~/.config/zsh/aliases.zsh
source ~/.config/zsh/fzf.zsh
source ~/.config/zsh/fzf_command.zsh

# fzf settings (bind to macos homebrew to keep it newest)
# source /usr/local/Cellar/fzf/0.35.1/shell/completion.zsh
# export FZF_DEFAULT_COMMAND='rg --files'

# fuck
#eval $(thefuck --alias)

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
